In [28]:
#Indexing and slicing matrices
import numpy as np

In [29]:
arr = np.array(
    [
        [1,2,3], #0
        [4,5,6], #1
        [7,8,9]  #2
    ]
)

In [30]:
arr[0][1] #2nd element of 1st row

2

In [33]:
#arr[d0, d1, d2, etc]
#select 2nd element from the 0th demesion
arr[0, 1]

2

In [36]:
#slicing from the 0th demesion to the 2nd
#exclusive [0, 2)
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#select all demension, 
#in those keep selecting from 0th to 2nd element 
#exclusive [0, 2)
arr[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
#select all demension, 
#in those keep selecting from 2th element onwards
arr[:, 2:]

array([[3],
       [6],
       [9]])

In [43]:
arr[:2, :2]

array([[1, 2],
       [4, 5]])

In [47]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr[1] = np.array([1,10,1])

In [49]:
arr

array([[ 1,  2,  3],
       [ 1, 10,  1],
       [ 7,  8,  9]])

In [50]:
arr[1] = 10

In [51]:
arr

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])